"""Fixtures backing the integration suite against a live PostgreSQL server.

Why this exists: every other test in the repo drives a hand-written fake
cursor, which proves that a code path *called* ``execute`` but never that the
SQL it built is valid. An invalid column reference, a Redshift-only construct
on the PostgreSQL path, or a broken GRANT passes a fake and fails on a user's
warehouse. These fixtures hand tests a real psycopg cursor so the server is
the judge.

Environment:

``DP_TEST_PG_DSN``
    Connection string. Defaults to the local test container
    (``postgresql://postgres:postgres@127.0.0.1:55432/dataplat_test``).

``DP_TEST_PG_REQUIRED``
    Truthy => an unreachable database is an ERROR, not a skip. CI sets it so
    these tests can never silently become decoration. Unset => skip, so a
    contributor without Docker still gets a green ``uv run pytest``.
"""

from __future__ import annotations

import itertools
import os
import pathlib
import re
from collections.abc import Iterator, Sequence
from typing import TYPE_CHECKING, LiteralString, NoReturn, Protocol

import pytest

if TYPE_CHECKING:
    from psycopg import Connection, Cursor
    from psycopg.rows import TupleRow

# psycopg ships in the optional "db" extra, so a bare `uv sync` leaves it out.
# Import failure must flow through the same skip/require gate as an
# unreachable server: swallowing it into an unconditional skip is exactly the
# lenient direction that would let CI stop testing anything.
try:
    import psycopg
    from psycopg import sql
    from psycopg.pq import TransactionStatus

    _PSYCOPG_MISSING: str | None = None
except ModuleNotFoundError as exc:  # pragma: no cover - depends on extras
    _PSYCOPG_MISSING = str(exc)


DEFAULT_DSN = "postgresql://postgres:postgres@127.0.0.1:55432/dataplat_test"

_DSN_ENV_VAR = "DP_TEST_PG_DSN"
_REQUIRED_ENV_VAR = "DP_TEST_PG_REQUIRED"

_START_CONTAINER_HINT = """\
Start one with:

    docker run -d --name dp-pg-test -p 55432:5432 \\
        -e POSTGRES_PASSWORD=postgres \\
        -e POSTGRES_DB=dataplat_test \\
        postgres:16 -c shared_preload_libraries=pg_stat_statements

Then, once per database:

    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

Or point DP_TEST_PG_DSN at a PostgreSQL you already have."""


# Relation inventory that `sample_schema` guarantees, keyed by name with the
# pg_class.relkind the server reports. Exported so tests can assert against
# the promise instead of re-hardcoding it.
SAMPLE_RELATIONS: dict[str, str] = {
    "orgs": "r",  # FK target, has a UNIQUE constraint
    "customers": "r",  # PK, FK, NOT NULL, CHECK, DEFAULT, comments, trigger
    "active_customers": "v",  # view
    "customers_per_org": "m",  # materialized view (populated)
    "events": "p",  # partitioned parent, RANGE on occurred_at
    "events_2024": "r",  # partition child
    "events_2025": "r",  # partition child
    "secrets": "r",  # RLS enabled + one policy
    "invoice_number_seq": "S",  # standalone sequence
}

# Non-relation objects `sample_schema` also creates, for the code paths that
# read them: two indexes beyond the primary keys (one partial), a trigger and
# its function, a policy, and one pg_default_acl entry.
SAMPLE_INDEXES: tuple[str, ...] = ("customers_org_id_idx", "customers_active_email_idx")
SAMPLE_TRIGGER = "customers_touch_updated_at"
SAMPLE_TRIGGER_FUNCTION = "touch_updated_at"
SAMPLE_POLICY = "secrets_owner_only"


# One statement per element. Kept separate rather than one semicolon-joined
# blob so a failure names the statement that broke instead of the whole script.
# `{s}` is the schema identifier, filled in via psycopg's sql.SQL.format.
_SAMPLE_DDL: tuple[LiteralString, ...] = (
    "CREATE SCHEMA {s}",
    "COMMENT ON SCHEMA {s} IS 'dataplat integration fixture'",
    """
    CREATE TABLE {s}.orgs (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text NOT NULL,
        CONSTRAINT orgs_name_key UNIQUE (name)
    )
    """,
    """
    CREATE TABLE {s}.customers (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        org_id integer NOT NULL
            REFERENCES {s}.orgs (id) ON DELETE CASCADE ON UPDATE RESTRICT,
        email text NOT NULL,
        status text NOT NULL DEFAULT 'active',
        lifetime_value numeric(12, 2) DEFAULT 0,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz,
        CONSTRAINT customers_status_check
            CHECK (status IN ('active', 'churned', 'trial'))
    )
    """,
    "COMMENT ON TABLE {s}.customers IS 'Customer master (integration fixture).'",
    "COMMENT ON COLUMN {s}.customers.email IS 'Primary contact address.'",
    "CREATE INDEX customers_org_id_idx ON {s}.customers (org_id)",
    # Partial index: exercises pg_index.indpred / pg_get_expr on the predicate.
    """
    CREATE INDEX customers_active_email_idx ON {s}.customers (email)
        WHERE status = 'active'
    """,
    "CREATE SEQUENCE {s}.invoice_number_seq START 1000",
    """
    INSERT INTO {s}.orgs (name)
    VALUES ('acme'), ('globex'), ('initech')
    """,
    """
    INSERT INTO {s}.customers (org_id, email, status, lifetime_value)
    SELECT
        (g % 3) + 1,
        'user' || g || '@example.com',
        CASE WHEN g % 4 = 0 THEN 'churned' ELSE 'active' END,
        g * 10.5
    FROM generate_series(1, 40) AS g
    """,
    # Created after the INSERTs so the matview is populated with real rows.
    """
    CREATE VIEW {s}.active_customers AS
    SELECT id, org_id, email, lifetime_value
    FROM {s}.customers
    WHERE status = 'active'
    """,
    "COMMENT ON VIEW {s}.active_customers IS 'Non-churned customers.'",
    """
    CREATE MATERIALIZED VIEW {s}.customers_per_org AS
    SELECT org_id, count(*) AS customer_count, sum(lifetime_value) AS total_value
    FROM {s}.customers
    GROUP BY org_id
    """,
    """
    CREATE TABLE {s}.events (
        event_id bigint GENERATED BY DEFAULT AS IDENTITY,
        occurred_at date NOT NULL,
        kind text NOT NULL DEFAULT 'click',
        payload jsonb,
        PRIMARY KEY (event_id, occurred_at)
    ) PARTITION BY RANGE (occurred_at)
    """,
    """
    CREATE TABLE {s}.events_2024 PARTITION OF {s}.events
        FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')
    """,
    """
    CREATE TABLE {s}.events_2025 PARTITION OF {s}.events
        FOR VALUES FROM ('2025-01-01') TO ('2026-01-01')
    """,
    """
    INSERT INTO {s}.events (occurred_at, kind, payload)
    SELECT
        DATE '2024-06-01' + (g % 400),
        'click',
        jsonb_build_object('n', g)
    FROM generate_series(1, 30) AS g
    """,
    """
    CREATE FUNCTION {s}.touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS '
    BEGIN
        NEW.updated_at := now();
        RETURN NEW;
    END;
    '
    """,
    """
    CREATE TRIGGER customers_touch_updated_at
        BEFORE UPDATE ON {s}.customers
        FOR EACH ROW EXECUTE FUNCTION {s}.touch_updated_at()
    """,
    """
    CREATE TABLE {s}.secrets (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_role name NOT NULL DEFAULT current_user,
        body text NOT NULL
    )
    """,
    "ALTER TABLE {s}.secrets ENABLE ROW LEVEL SECURITY",
    """
    CREATE POLICY secrets_owner_only ON {s}.secrets
        FOR ALL
        USING (owner_role = current_user)
        WITH CHECK (owner_role = current_user)
    """,
    "INSERT INTO {s}.secrets (body) VALUES ('alpha'), ('beta')",
    # Without ANALYZE, pg_class.reltuples is -1 ("never analyzed") and every
    # row-estimate assertion would be vacuous. ANALYZE is allowed inside a
    # transaction (VACUUM is not) and its in-place pg_class update is visible
    # to this transaction immediately.
    "ANALYZE {s}.orgs, {s}.customers, {s}.events, {s}.secrets",
    # Last on purpose: default privileges only affect relations created *after*
    # this runs, so nothing above inherits a PUBLIC grant. It exists so the
    # pg_default_acl / aclexplode path has a row to find.
    "ALTER DEFAULT PRIVILEGES IN SCHEMA {s} GRANT SELECT ON TABLES TO PUBLIC",
)


_SCHEMA_COUNTER = itertools.count()
_ROLE_COUNTER = itertools.count()

# Postgres truncates identifiers at 63 bytes. Uniqueness therefore goes at the
# FRONT of generated names: truncation then only shortens the human-readable
# tail and can never collapse two distinct objects onto one name.
_MAX_IDENT_LEN = 63


def _slug(raw: str) -> str:
    """Reduce a test name to identifier-safe lowercase ASCII."""
    return re.sub(r"[^a-z0-9]+", "_", raw.lower()).strip("_")


def _unique_ident(kind: str, counter: itertools.count[int], label: str) -> str:
    """Build a collision-proof identifier for a throwaway object.

    Roles are cluster-wide and schemas survive a skipped rollback, so the pid
    guards against parallel runs against the same server while the counter
    guards against two objects inside one process.
    """
    name = f"dp_it_{kind}{next(counter)}_{os.getpid()}_{_slug(label)}"
    return name[:_MAX_IDENT_LEN].rstrip("_")


def _truthy(raw: str | None) -> bool:
    """Interpret an env var as a boolean, defaulting to False when unset."""
    if raw is None:
        return False
    return raw.strip().lower() not in {"", "0", "false", "no", "off"}


def _redact(dsn: str) -> str:
    """Strip the password from a DSN so failure messages stay log-safe."""
    return re.sub(r"(://[^:/@]+):[^@]*@", r"\1:***@", dsn)


def _unavailable(reason: str, dsn: str) -> NoReturn:
    """Skip, or ERROR when DP_TEST_PG_REQUIRED is set.

    This is the load-bearing branch of the harness. Getting it wrong in the
    lenient direction (always skipping) means CI reports green while executing
    none of the SQL these tests exist to validate, so the required path raises
    instead of skipping.
    """
    message = (
        f"PostgreSQL for the integration suite is unavailable: {reason}\n"
        f"{_DSN_ENV_VAR}={_redact(dsn)}\n\n"
        f"{_START_CONTAINER_HINT}\n\n"
        f"Set {_REQUIRED_ENV_VAR}=1 to turn this skip into a hard failure."
    )
    if _truthy(os.environ.get(_REQUIRED_ENV_VAR)):
        # pytest.fail inside a fixture is reported as an ERROR at setup, which
        # is what "never silently decoration" requires.
        pytest.fail(message, pytrace=False)
    pytest.skip(message)


def pytest_collection_modifyitems(items: list[pytest.Item]) -> None:
    """Mark everything under tests/integration/ as ``integration``.

    Test modules here also declare ``pytestmark = pytest.mark.integration``;
    this is the safety net that keeps ``-m 'not integration'`` airtight if a
    new module forgets to. Filtered by path because the hook is handed the
    whole session's items, not just this directory's.
    """
    here = pathlib.Path(__file__).parent
    for item in items:
        path = getattr(item, "path", None)
        if path is not None and here in pathlib.Path(path).parents:
            item.add_marker(pytest.mark.integration)


@pytest.fixture(scope="session")
def pg_dsn() -> str:
    """Resolved DSN for the test server, or skip/ERROR if it is unusable.

    Probes the server once per session so an unreachable database is reported
    by this fixture rather than as a confusing failure deep inside a test.
    """
    dsn = os.environ.get(_DSN_ENV_VAR) or DEFAULT_DSN

    if _PSYCOPG_MISSING is not None:
        _unavailable(
            f"psycopg is not installed ({_PSYCOPG_MISSING}). "
            "Install the optional extra: uv sync --all-extras",
            dsn,
        )

    try:
        with psycopg.connect(dsn, connect_timeout=5) as probe:
            probe.execute("SELECT 1")
    except psycopg.Error as exc:
        _unavailable(str(exc).strip(), dsn)

    return dsn


@pytest.fixture(scope="session")
def pg_conn(pg_dsn: str) -> Iterator[Connection[TupleRow]]:
    """Session-wide psycopg connection with autocommit OFF.

    Row factory is left at psycopg's default (plain tuples) because the
    services under test unpack rows positionally, e.g. ``IndexInfo(*row)``.
    """
    conn = psycopg.connect(
        pg_dsn,
        autocommit=False,
        application_name="dataplat-integration-tests",
    )
    try:
        yield conn
    finally:
        conn.rollback()
        conn.close()


@pytest.fixture
def pg_cursor(pg_conn: Connection[TupleRow]) -> Iterator[Cursor[TupleRow]]:
    """Cursor inside a transaction that is ROLLED BACK after the test.

    Isolation is what makes the suite safe to run in any order: a test that
    fails halfway through its DDL cannot leave objects behind to poison the
    next one.

    Rollback is viable for the role suites because CREATE ROLE, DROP ROLE,
    GRANT and ALTER ... OWNER TO are all transactional in PostgreSQL -- a
    rolled-back transaction leaves no trace of them in the cluster-wide
    catalogs. Statements that genuinely cannot run inside a transaction block
    (CREATE INDEX CONCURRENTLY, VACUUM, CREATE DATABASE, ALTER SYSTEM) are what
    ``pg_autocommit_cursor`` exists for.
    """
    # Clear anything a previous test left mid-transaction before handing the
    # cursor over, so this test starts from a known-clean transaction state.
    pg_conn.rollback()
    cursor = pg_conn.cursor()
    try:
        yield cursor
    finally:
        cursor.close()
        pg_conn.rollback()


@pytest.fixture(scope="session")
def _pg_autocommit_conn(pg_dsn: str) -> Iterator[Connection[TupleRow]]:
    """Second connection in autocommit mode.

    Separate from ``pg_conn`` on purpose: psycopg refuses to toggle autocommit
    while a transaction is open, so sharing one connection would make the two
    cursor fixtures fight over connection state.
    """
    conn = psycopg.connect(
        pg_dsn,
        autocommit=True,
        application_name="dataplat-integration-tests-autocommit",
    )
    try:
        yield conn
    finally:
        conn.close()


@pytest.fixture
def pg_autocommit_cursor(
    _pg_autocommit_conn: Connection[TupleRow],
) -> Iterator[Cursor[TupleRow]]:
    """Cursor with autocommit ON, for statements a transaction cannot hold.

    Nothing is rolled back here -- that is the whole point -- so a test using
    this fixture owns cleanup of anything it creates.
    """
    cursor = _pg_autocommit_conn.cursor()
    try:
        yield cursor
    finally:
        cursor.close()


def _txn_usable(conn: Connection[TupleRow]) -> bool:
    """True when the connection can still execute cleanup statements.

    A service function that hit invalid SQL leaves the transaction aborted, and
    every further statement fails until rollback. Teardown checks this instead
    of raising a second, misleading error on the way out.
    """
    return conn.info.transaction_status is not TransactionStatus.INERROR


@pytest.fixture
def sample_schema(
    request: pytest.FixtureRequest, pg_cursor: Cursor[TupleRow]
) -> Iterator[str]:
    """Create a uniquely-named schema of realistic objects; yield its name.

    Built through ``pg_cursor``, so the objects live in that test's
    transaction and vanish on its rollback. The name embeds the pid, a counter
    and the test name, so even a skipped rollback cannot collide with another
    test or another parallel run.

    Contents (see ``SAMPLE_RELATIONS`` and friends): tables with a primary key,
    a foreign key with ON DELETE/ON UPDATE actions, NOT NULL, CHECK and UNIQUE
    constraints, a column DEFAULT and identity columns, table/column/view and
    schema COMMENTs, a secondary index and a partial index, a view, a populated
    materialized view, a RANGE-partitioned table with two partitions, a
    standalone sequence, a trigger with its plpgsql function, a table with RLS
    enabled plus a policy, and one ``ALTER DEFAULT PRIVILEGES`` entry. Tables
    are ANALYZEd, so row estimates and sizes are non-zero.
    """
    schema = _unique_ident("s", _SCHEMA_COUNTER, request.node.name)
    identifier = sql.Identifier(schema)

    for statement in _SAMPLE_DDL:
        pg_cursor.execute(sql.SQL(statement).format(s=identifier))

    try:
        yield schema
    finally:
        # Rollback in pg_cursor's teardown is the authoritative cleanup; this
        # DROP only matters for a test that committed on purpose.
        if _txn_usable(pg_cursor.connection):
            pg_cursor.execute(
                sql.SQL("DROP SCHEMA IF EXISTS {s} CASCADE").format(s=identifier)
            )


class TempRoleFactory(Protocol):
    """Signature of the ``temp_role`` fixture."""

    def __call__(
        self,
        suffix: str = ...,
        *,
        login: bool = ...,
        password: str | None = ...,
        options: Sequence[str] = ...,
    ) -> str: ...


_ROLE_OPTION_RE = re.compile(r"^[A-Za-z]+$")


@pytest.fixture
def temp_role(
    request: pytest.FixtureRequest, pg_cursor: Cursor[TupleRow]
) -> Iterator[TempRoleFactory]:
    """Factory creating throwaway roles; yields each generated role name.

    ``suffix`` is a readable label appended to the generated name.
    ``login`` picks LOGIN vs NOLOGIN, ``password`` adds a PASSWORD clause when
    not None, and ``options`` splices in extra bare role keywords
    (e.g. ``("CREATEDB", "INHERIT")``).

    Roles are cluster-wide, so names embed the pid and a counter. Creation goes
    through ``pg_cursor``: CREATE ROLE is transactional, so the rollback at the
    end of the test removes the role together with anything it came to own,
    which no explicit DROP could guarantee once the role had grants or objects.
    """
    created: list[str] = []

    def make(
        suffix: str = "role",
        *,
        login: bool = False,
        password: str | None = None,
        options: Sequence[str] = (),
    ) -> str:
        name = _unique_ident("r", _ROLE_COUNTER, f"{request.node.name}_{suffix}")
        clauses: list[sql.Composable] = [
            sql.SQL("LOGIN") if login else sql.SQL("NOLOGIN")
        ]
        if password is not None:
            clauses.append(sql.SQL("PASSWORD {}").format(password))
        for option in options:
            # Role options are bare keywords, so they cannot be parameterized.
            # Reject anything that is not a plain word rather than interpolate
            # it: a typo should surface here, not as opaque syntax error SQL.
            if not _ROLE_OPTION_RE.match(option):
                raise ValueError(f"invalid role option: {option!r}")
            clauses.append(sql.SQL(option.upper()))
        pg_cursor.execute(
            sql.SQL("CREATE ROLE {role} {opts}").format(
                role=sql.Identifier(name), opts=sql.SQL(" ").join(clauses)
            )
        )
        created.append(name)
        return name

    try:
        yield make
    finally:
        # Reverse order so a role granted into another is removed first. As
        # with sample_schema, the rollback is what really guarantees cleanup;
        # skip the DROPs entirely once the transaction is already aborted.
        if _txn_usable(pg_cursor.connection):
            for name in reversed(created):
                pg_cursor.execute(
                    sql.SQL("DROP OWNED BY {role} CASCADE").format(
                        role=sql.Identifier(name)
                    )
                )
                pg_cursor.execute(
                    sql.SQL("DROP ROLE IF EXISTS {role}").format(
                        role=sql.Identifier(name)
                    )
                )
