"""Rendering for ``dp db describe``.

Takes dataclasses from :mod:`dataplat.services.db.describe` and prints
them with Rich. No SQL or connection handling in this module.

Design goal: a printed-report feel — typography-first, generous whitespace,
numbered sections with captions, a title card on top. Inspired by a
well-typeset corporate data-dictionary PDF.

Everything rendered here — identifiers, comments, constraint bodies, view SQL —
comes from the warehouse, so it is either a :func:`cell` (table cells, whole
values) or passed through :func:`esc` before it is interpolated into one of our
markup strings. See :mod:`dataplat.cli.db._report` for the rule that applies to
the shared report helpers.
"""

from __future__ import annotations

import dataclasses
import json
from typing import Any

import typer
from rich.columns import Columns
from rich.console import Console
from rich.syntax import Syntax
from rich.text import Text

from dataplat.cli._render import cell, esc
from dataplat.cli.db._common import (
    ConnCliParams,
    DatabaseOption,
    EngineOption,
    EnvPrefixOption,
    HostOption,
    JsonOption,
    PasswordOption,
    PortOption,
    SslmodeOption,
    TargetOption,
    UserOption,
    db_session,
    resolve_any_params_or_exit,
)
from dataplat.cli.db._report import (
    DASH as _DASH,
)
from dataplat.cli.db._report import (
    SectionCounter as _SectionCounter,
)
from dataplat.cli.db._report import (
    dim as _dim,
)
from dataplat.cli.db._report import (
    fmt_rows as _fmt_rows,
)
from dataplat.cli.db._report import (
    fmt_size as _fmt_size,
)
from dataplat.cli.db._report import (
    fmt_size_plain as _fmt_size_plain,
)
from dataplat.cli.db._report import (
    indent as _indent,
)
from dataplat.cli.db._report import (
    print_section_heading as _print_section_heading,
)
from dataplat.cli.db._report import (
    report_table as _report_table,
)
from dataplat.cli.db._report import (
    title_card as _title_card,
)
from dataplat.services.db.capabilities import capabilities_for
from dataplat.services.db.connection import SqlEngine
from dataplat.services.db.describe import (
    DefaultPrivilegeGrant,
    NotApplicable,
    ObjectKind,
    PartitioningInfo,
    PrivilegeGrant,
    SchemaDescription,
    TableDescription,
    TargetNotFoundError,
    ViewDescription,
    describe_schema,
    describe_table,
    describe_view,
    resolve_target,
)

Description = TableDescription | ViewDescription | SchemaDescription


# ---------------------------------------------------------------------------
# Section captions
# ---------------------------------------------------------------------------

_CAPTION_COLUMNS = "Column definitions, types, nullability, defaults."
_CAPTION_INDEXES = "Indexes defined on this relation."
_CAPTION_CONSTRAINTS = "Foreign keys, unique constraints, and check constraints."
_CAPTION_PARTITIONING_ROOT = "Partitioning strategy and child partitions."
_CAPTION_PARTITIONING_CHILD = "This relation is a partition of another table."
_CAPTION_PRIVILEGES = "Access grants other than ownership."
_CAPTION_TRIGGERS = "Triggers fired on INSERT / UPDATE / DELETE."
_CAPTION_RLS = "RLS status and applicable policies."
_CAPTION_DEPENDENCIES = (
    "Relations this view reads from, and relations that read from this view."
)
_CAPTION_DEFINITION = "View SQL."
_CAPTION_SCHEMA_CONTENTS = "Objects that live in this schema."
_CAPTION_SCHEMA_PRIVILEGES = "Access grants on this schema (USAGE, CREATE)."
_CAPTION_SCHEMA_DEFAULT_PRIVILEGES = (
    "Privileges that future objects in this schema inherit "
    "(set via ALTER DEFAULT PRIVILEGES)."
)
_CAPTION_SCHEMA_HIGHLIGHTS = "Largest objects by total size."
_CAPTION_DISTRIBUTION = "Redshift distribution style and sort keys."
_CAPTION_TABLE_STATS = "Redshift storage statistics."
# The one caption that has to argue rather than label: the whole reason this
# section exists is that a *missing* section and an *empty* one say different
# things, and a reader cannot tell them apart without being told.
_CAPTION_NOT_APPLICABLE = (
    "Sections this engine has no concept of. Absent here means the concept does "
    "not exist — not that nothing is configured."
)


# ---------------------------------------------------------------------------
# Small formatting helpers
# ---------------------------------------------------------------------------


def _shorten_identity(default: str | None) -> str | None:
    if default == "GENERATED ALWAYS AS IDENTITY":
        return "identity (always)"
    if default == "GENERATED BY DEFAULT AS IDENTITY":
        return "identity (default)"
    return default


def _strip_partition_bounds(bounds: str | None) -> str:
    """``FOR VALUES IN ('x')`` → ``'x'``; ranges and DEFAULT pass through."""
    if not bounds:
        return ""
    b = bounds.strip()
    if b == "DEFAULT" or b.startswith("FOR VALUES FROM"):
        return b
    prefix = "FOR VALUES IN ("
    if b.startswith(prefix) and b.endswith(")"):
        return b[len(prefix) : -1].strip()
    return b


def _summarize_partition_key(key: str | None, strategy: str | None) -> tuple[str, str]:
    """Return ``(strategy_label, columns_label)`` for the summary line."""
    if not key:
        return (strategy or "", "")
    for prefix in ("LIST", "RANGE", "HASH"):
        lower_prefix = f"{prefix} ("
        if key.upper().startswith(lower_prefix):
            inner = key[len(lower_prefix) :].rstrip(")").strip()
            return (prefix, inner)
    return (strategy or "", key)


def _kind_label(kind: ObjectKind, *, partitioned: bool = False) -> str:
    if kind == ObjectKind.matview:
        return "Materialized View"
    if kind == ObjectKind.view:
        return "View"
    if kind == ObjectKind.schema:
        return "Schema"
    if partitioned:
        return "Partitioned Table"
    return "Table"


def _filtered_grants(grants: list[PrivilegeGrant]) -> list[PrivilegeGrant]:
    """Drop OWNER rows (owner is shown in the header)."""
    return [g for g in grants if g.privilege != "OWNER"]


# ---------------------------------------------------------------------------
# Title-card builders for each kind
# ---------------------------------------------------------------------------


def _table_title_metadata(desc: TableDescription) -> list[tuple[str, str]]:
    hdr = desc.header
    pairs: list[tuple[str, str]] = []
    if hdr.owner:
        pairs.append(("Owner", esc(hdr.owner)))
    if hdr.tablespace:
        pairs.append(("Tablespace", esc(hdr.tablespace)))
    if hdr.total_size is not None:
        parts: list[str] = []
        if hdr.table_size is not None:
            parts.append(f"table {_fmt_size_plain(hdr.table_size)}")
        if hdr.index_size is not None:
            parts.append(f"index {_fmt_size_plain(hdr.index_size)}")
        if hdr.toast_size is not None:
            parts.append(f"toast {_fmt_size_plain(hdr.toast_size)}")
        size = _fmt_size(hdr.total_size)
        if parts:
            size = f"{size}  {_dim('(' + ' · '.join(parts) + ')')}"
        pairs.append(("Size", size))
    if hdr.row_estimate is not None and hdr.row_estimate >= 0:
        pairs.append(("Rows (est)", _fmt_rows(hdr.row_estimate)))
    if desc.partitioning.children:
        pairs.append(("Partitions", str(len(desc.partitioning.children))))
    if hdr.comment:
        pairs.append(("Comment", esc(hdr.comment)))
    return pairs


def _view_title_metadata(desc: ViewDescription) -> list[tuple[str, str]]:
    hdr = desc.header
    pairs: list[tuple[str, str]] = []
    if hdr.owner:
        pairs.append(("Owner", esc(hdr.owner)))
    pairs.append(("Updatable", "yes" if desc.definition.is_updatable else "no"))
    if desc.definition.check_option:
        pairs.append(("Check option", esc(desc.definition.check_option)))
    if hdr.comment:
        pairs.append(("Comment", esc(hdr.comment)))
    return pairs


def _schema_title_metadata(desc: SchemaDescription) -> list[tuple[str, str]]:
    hdr = desc.header
    counts: dict[str, int] = {}
    for item in desc.contents:
        counts[item.kind] = counts.get(item.kind, 0) + 1

    pairs: list[tuple[str, str]] = []
    if hdr.owner:
        pairs.append(("Owner", esc(hdr.owner)))
    if counts:
        parts = []
        for kind in sorted(counts):
            n = counts[kind]
            label = kind if n == 1 else f"{kind}s"
            parts.append(f"{n} {esc(label)}")
        pairs.append(("Contents", " · ".join(parts)))
    total_size = sum(item.size_bytes or 0 for item in desc.contents)
    if total_size > 0:
        pairs.append(("Size", _fmt_size(total_size)))
    total_rows = sum(
        item.row_estimate or 0
        for item in desc.contents
        if item.row_estimate is not None and item.row_estimate >= 0
    )
    if total_rows > 0:
        pairs.append(("Rows (est)", _fmt_rows(total_rows)))
    if hdr.comment:
        pairs.append(("Comment", esc(hdr.comment)))
    return pairs


# ---------------------------------------------------------------------------
# Columns section
# ---------------------------------------------------------------------------


def _render_columns(
    console: Console,
    counter: _SectionCounter,
    desc: TableDescription | ViewDescription,
    engine: SqlEngine,
) -> None:
    _print_section_heading(console, counter, "Columns", _CAPTION_COLUMNS)

    is_table = isinstance(desc, TableDescription)
    width = console.size.width or 80

    has_default = is_table and any(c.default for c in desc.columns)
    has_fk = is_table and any(c.fk_target_table for c in desc.columns)
    has_comment = any(c.comment for c in desc.columns)
    has_encoding = engine == SqlEngine.redshift and any(
        c.encoding for c in desc.columns
    )

    # Responsive drop order: Comment → FK → Default → Encoding.
    budget = width - 44  # rough slack for mandatory columns + gutter
    if has_comment and budget < 20:
        has_comment = False
    elif has_comment:
        budget -= max(20, width // 6) + 2
    if has_fk and budget < 18:
        has_fk = False
    elif has_fk:
        budget -= 22
    if has_default and budget < 14:
        has_default = False
    if has_encoding and budget < 10:
        has_encoding = False

    comment_width = max(20, width // 6)

    table = _report_table(zebra=len(desc.columns) > 5)
    table.add_column("#", justify="right", style="dim", width=3)
    table.add_column("Name")
    table.add_column("Type", style="dim")
    table.add_column("Nullable")
    if is_table:
        if has_default:
            table.add_column("Default", overflow="fold")
        table.add_column("PK")
        if has_fk:
            table.add_column("FK", overflow="fold")
    if has_comment:
        table.add_column("Comment", overflow="fold")
    if has_encoding:
        table.add_column("Encoding")

    for c in desc.columns:
        row: list[str | Text] = [
            str(c.ordinal),
            cell(c.name),
            cell(c.data_type),
            _dim("not null") if not c.nullable else "",
        ]
        if is_table:
            if has_default:
                row.append(cell(_shorten_identity(c.default) or ""))
            row.append("[cyan]●[/cyan]" if c.is_primary_key else "")
            if has_fk:
                if c.fk_target_table:
                    fk = esc(f"{c.fk_target_table}({c.fk_target_column})")
                    row.append(f"{_dim('→')} {_dim(fk)}")
                else:
                    row.append("")
        if has_comment:
            row.append(cell(c.comment or "", max_length=comment_width))
        if has_encoding:
            row.append(cell(c.encoding or ""))
        table.add_row(*row)

    console.print(_indent(table))

    if isinstance(desc, TableDescription):
        pk = desc.constraints.primary_key
        caption_bits: list[str] = []
        if pk is not None:
            caption_bits.append(
                f"Primary key: {esc(pk.name)} ({esc(', '.join(pk.columns))})"
            )
        caption_bits.append(f"{len(desc.columns)} columns")
        if desc.header.row_estimate is not None and desc.header.row_estimate >= 0:
            caption_bits.append(
                f"~{_fmt_rows(desc.header.row_estimate, colored=False)} rows"
            )
        console.print()
        console.print(f"  [dim]{'  ·  '.join(caption_bits)}[/dim]")


# ---------------------------------------------------------------------------
# Indexes section
# ---------------------------------------------------------------------------


def _render_indexes(
    console: Console, counter: _SectionCounter, desc: TableDescription
) -> None:
    if not desc.indexes:
        return
    _print_section_heading(console, counter, "Indexes", _CAPTION_INDEXES)

    has_predicate = any(idx.predicate for idx in desc.indexes)
    table = _report_table(zebra=len(desc.indexes) > 5)
    table.add_column("Name", overflow="fold")
    table.add_column("Kind")
    table.add_column("Columns", overflow="fold")
    table.add_column("Method", style="dim")
    table.add_column("Size", justify="right")
    if has_predicate:
        table.add_column("Predicate", overflow="fold")

    def _key(idx: Any) -> tuple[int, int, str]:
        return (0 if idx.primary else 1, 0 if idx.unique else 1, idx.name)

    for idx in sorted(desc.indexes, key=_key):
        if idx.primary:
            kind = "[cyan]PK[/cyan]"
        elif idx.unique:
            kind = "[bold]UNIQUE[/bold]"
        else:
            kind = _dim("INDEX")
        row: list[str | Text] = [
            cell(idx.name),
            kind,
            cell(", ".join(idx.columns)),
            cell(idx.method),
            _fmt_size(idx.size_bytes),
        ]
        if has_predicate:
            row.append(cell(idx.predicate or ""))
        table.add_row(*row)
    console.print(_indent(table))


# ---------------------------------------------------------------------------
# Constraints section
# ---------------------------------------------------------------------------


def _render_constraints(
    console: Console, counter: _SectionCounter, desc: TableDescription
) -> None:
    cons = desc.constraints
    if not (cons.foreign_keys or cons.unique_constraints or cons.check_constraints):
        return
    _print_section_heading(console, counter, "Constraints", _CAPTION_CONSTRAINTS)

    total_rows = (
        len(cons.foreign_keys)
        + len(cons.unique_constraints)
        + len(cons.check_constraints)
    )
    table = _report_table(zebra=total_rows > 5)
    table.add_column("Kind")
    table.add_column("Name", overflow="fold")
    table.add_column("Details", overflow="fold")

    for fk in cons.foreign_keys:
        cols = esc(", ".join(fk.columns))
        ref = esc(f"{fk.referenced_table}({', '.join(fk.referenced_columns)})")
        body = f"{cols} {_dim('→')} {ref}"
        extras: list[str] = []
        if fk.on_delete and fk.on_delete != "NO ACTION":
            extras.append(f"ON DELETE {esc(fk.on_delete)}")
        if fk.on_update and fk.on_update != "NO ACTION":
            extras.append(f"ON UPDATE {esc(fk.on_update)}")
        if fk.deferrable:
            extras.append("DEFERRABLE")
        if extras:
            body = f"{body}  {_dim(' '.join(extras))}"
        table.add_row("FOREIGN KEY", cell(fk.name), body)
    for u in cons.unique_constraints:
        table.add_row("UNIQUE", cell(u.name), cell(u.definition))
    for ck in cons.check_constraints:
        table.add_row("CHECK", cell(ck.name), cell(ck.definition))

    console.print(_indent(table))


# ---------------------------------------------------------------------------
# Partitioning section
# ---------------------------------------------------------------------------


def _render_partitioning(
    console: Console, counter: _SectionCounter, info: PartitioningInfo
) -> None:
    if info.parent:
        _print_section_heading(
            console, counter, "Partitioning", _CAPTION_PARTITIONING_CHILD
        )
        console.print(f"  Partition of [cyan]{esc(info.parent)}[/cyan]")
        return
    if not info.children and not info.partition_key:
        return
    _print_section_heading(console, counter, "Partitioning", _CAPTION_PARTITIONING_ROOT)
    raw_strategy, raw_columns = _summarize_partition_key(
        info.partition_key, info.strategy
    )
    # Both halves are catalog text (the key can name arbitrary columns).
    strategy, columns = esc(raw_strategy), esc(raw_columns)
    n = len(info.children)
    summary_bits: list[str] = []
    if strategy or columns:
        if strategy and columns:
            summary_bits.append(f"Strategy: [bold]{strategy}[/bold] on {columns}")
        elif strategy:
            summary_bits.append(f"Strategy: [bold]{strategy}[/bold]")
        elif columns:
            summary_bits.append(f"on {columns}")
    if n:
        summary_bits.append(f"{n} partitions")
    if summary_bits:
        console.print(f"  {'  ·  '.join(summary_bits)}")

    if info.children:
        console.print()
        table = _report_table(zebra=len(info.children) > 5)
        table.add_column("Name")
        table.add_column("Bounds", overflow="fold")
        for child, bounds in info.children:
            table.add_row(cell(child), cell(_strip_partition_bounds(bounds)))
        console.print(_indent(table))


# ---------------------------------------------------------------------------
# Privileges section
# ---------------------------------------------------------------------------


def _render_privileges(
    console: Console, counter: _SectionCounter, grants: list[PrivilegeGrant]
) -> None:
    filtered = _filtered_grants(grants)
    if not filtered:
        return
    _print_section_heading(console, counter, "Privileges", _CAPTION_PRIVILEGES)
    table = _report_table(zebra=len(filtered) > 5)
    table.add_column("Grantee")
    table.add_column("Privilege")
    table.add_column("Grantor", style="dim")
    for g in filtered:
        priv = g.privilege + (" *" if g.with_grant_option else "")
        table.add_row(cell(g.grantee), cell(priv), cell(g.grantor or ""))
    console.print(_indent(table))


# ---------------------------------------------------------------------------
# Triggers / RLS
# ---------------------------------------------------------------------------


def _render_triggers(
    console: Console,
    counter: _SectionCounter,
    desc: TableDescription | ViewDescription,
    title: str,
) -> None:
    if not desc.triggers:
        return
    _print_section_heading(console, counter, title, _CAPTION_TRIGGERS)
    table = _report_table(zebra=len(desc.triggers) > 5)
    for col in ("Name", "Timing", "Events", "Definition"):
        table.add_column(col, overflow="fold")
    for t in desc.triggers:
        table.add_row(cell(t.name), cell(t.timing), cell(t.events), cell(t.function))
    console.print(_indent(table))


def _render_rls(
    console: Console, counter: _SectionCounter, desc: TableDescription
) -> None:
    if not (desc.policies_enabled or desc.policies):
        return
    _print_section_heading(console, counter, "Row-level security", _CAPTION_RLS)
    if desc.policies_enabled and not desc.policies:
        console.print(_indent(_dim("RLS enabled, no policies.")))
        return
    console.print(f"  Enabled: {'yes' if desc.policies_enabled else 'no'}")
    if desc.policies:
        console.print()
        table = _report_table(zebra=len(desc.policies) > 5)
        for col in ("Name", "Command", "Roles", "USING", "WITH CHECK"):
            table.add_column(col, overflow="fold")
        for p in desc.policies:
            table.add_row(
                cell(p.name),
                cell(p.command),
                cell(", ".join(p.roles)),
                cell(p.using or ""),
                cell(p.with_check or ""),
            )
        console.print(_indent(table))


# ---------------------------------------------------------------------------
# View dependencies
# ---------------------------------------------------------------------------


def _render_view_dependencies(
    console: Console, counter: _SectionCounter, desc: ViewDescription
) -> None:
    if not desc.upstream and not desc.downstream:
        return
    _print_section_heading(console, counter, "Dependencies", _CAPTION_DEPENDENCIES)

    def _block(title: str, edges: list[Any]) -> str:
        lines = [f"[dim italic]{title}[/dim italic]"]
        if not edges:
            lines.append(f"  {_DASH}")
        else:
            for e in edges:
                lines.append(
                    f"  [dim]•[/dim] {esc(e.qualified_name)} "
                    f"{_dim('(' + esc(e.kind) + ')')}"
                )
        return "\n".join(lines)

    left = _block("Reads from", desc.upstream)
    right = _block("Read by", desc.downstream)

    width = console.size.width or 80
    if desc.upstream and desc.downstream and width >= 100:
        console.print(_indent(Columns([left, right], padding=(0, 6), expand=False)))
    else:
        console.print(_indent(left))
        if desc.downstream:
            console.print()
            console.print(_indent(right))


# ---------------------------------------------------------------------------
# Redshift extras
# ---------------------------------------------------------------------------


def _render_redshift_extras(
    console: Console,
    counter: _SectionCounter,
    desc: TableDescription,
    engine: SqlEngine,
) -> None:
    if engine != SqlEngine.redshift:
        return
    if desc.redshift_distribution:
        rd = desc.redshift_distribution
        _print_section_heading(
            console, counter, "Distribution & sort", _CAPTION_DISTRIBUTION
        )
        parts = [
            f"{_dim('Diststyle')} {esc(rd.diststyle)}",
            f"{_dim('Distkey')} {esc(rd.distkey) or '—'}",
            f"{_dim('Sortkey style')} {esc(rd.sortkey_style) or '—'}",
            f"{_dim('Sortkeys')} {esc(', '.join(rd.sortkeys)) or '—'}",
        ]
        console.print(f"  {'  ·  '.join(parts)}")
    if desc.redshift_stats:
        rs = desc.redshift_stats
        _print_section_heading(console, counter, "Table stats", _CAPTION_TABLE_STATS)
        parts = [
            f"{_dim('Skew rows')} {rs.skew_rows}",
            f"{_dim('Unsorted')} {rs.unsorted_pct}%",
            f"{_dim('Stats off')} {rs.stats_off}",
        ]
        console.print(f"  {'  ·  '.join(parts)}")


# ---------------------------------------------------------------------------
# Sections the engine has no concept of
# ---------------------------------------------------------------------------


def _render_not_applicable(
    console: Console,
    counter: _SectionCounter,
    items: list[NotApplicable],
    engine: SqlEngine,
) -> None:
    """List the sections this engine cannot have, and why.

    Rendered as a real numbered section rather than a footnote, because it
    carries the same weight as the data sections: on DuckDB, "no Privileges
    section" is the answer to "who can read this table", and the reader has to
    be able to see that they were told rather than that something failed.

    Empty for PostgreSQL and Redshift today, which is why nothing about the
    existing reports moves.
    """
    if not items:
        return
    label = capabilities_for(engine).label
    _print_section_heading(
        console, counter, f"Not applicable on {label}", _CAPTION_NOT_APPLICABLE
    )
    table = _report_table(zebra=len(items) > 5)
    table.add_column("Section")
    table.add_column("Why", overflow="fold")
    for item in items:
        # cell() on both, though both strings are ours today: the reasons are
        # sourced from capabilities.py and one may yet interpolate a catalog
        # name, and a renderer that trusts *some* of its input is the one that
        # breaks later. Same rule as every other cell in this module.
        table.add_row(cell(item.section), cell(item.reason))
    console.print(_indent(table))


# ---------------------------------------------------------------------------
# Top-level renderers
# ---------------------------------------------------------------------------


def _print_title_card_and_gap(
    console: Console,
    *,
    title: str,
    subtitle: str,
    metadata: list[tuple[str, str]],
) -> None:
    card = _title_card(console, title=title, subtitle=subtitle, metadata=metadata)
    console.print(card)
    # Two blank lines between title card and section 1.
    console.print()
    console.print()


def _render_table_description(
    console: Console, desc: TableDescription, engine: SqlEngine
) -> None:
    partitioned = bool(desc.partitioning.children)
    kind = _kind_label(desc.ref.kind, partitioned=partitioned)
    qualified = esc(f"{desc.header.schema}.{desc.header.name}")
    _print_title_card_and_gap(
        console,
        title=qualified,
        subtitle=kind,
        metadata=_table_title_metadata(desc),
    )

    counter = _SectionCounter()
    _render_columns(console, counter, desc, engine)
    _render_indexes(console, counter, desc)
    _render_constraints(console, counter, desc)
    _render_partitioning(console, counter, desc.partitioning)
    _render_privileges(console, counter, desc.privileges)
    _render_triggers(console, counter, desc, "Triggers")
    _render_rls(console, counter, desc)
    _render_redshift_extras(console, counter, desc, engine)
    _render_not_applicable(console, counter, desc.not_applicable, engine)

    # Matview definition last (can be long).
    if desc.definition:
        _print_section_heading(console, counter, "Definition", _CAPTION_DEFINITION)
        syntax = Syntax(
            desc.definition,
            "sql",
            theme="monokai",
            word_wrap=True,
            line_numbers=True,
            padding=(0, 2),
        )
        console.print(_indent(syntax))


def _render_view_description(
    console: Console, desc: ViewDescription, engine: SqlEngine
) -> None:
    qualified = esc(f"{desc.header.schema}.{desc.header.name}")
    kind = "Materialized View" if desc.ref.kind == ObjectKind.matview else "View"
    _print_title_card_and_gap(
        console,
        title=qualified,
        subtitle=kind,
        metadata=_view_title_metadata(desc),
    )

    counter = _SectionCounter()
    _render_columns(console, counter, desc, engine)
    _render_view_dependencies(console, counter, desc)
    _render_privileges(console, counter, desc.privileges)
    _render_triggers(console, counter, desc, "Triggers (INSTEAD OF)")
    _render_not_applicable(console, counter, desc.not_applicable, engine)

    # Definition LAST — it can be hundreds of lines.
    _print_section_heading(console, counter, "Definition", _CAPTION_DEFINITION)
    syntax = Syntax(
        desc.definition.sql,
        "sql",
        theme="monokai",
        word_wrap=True,
        line_numbers=True,
        padding=(0, 2),
    )
    console.print(_indent(syntax))


def _render_schema_privileges(
    console: Console,
    counter: _SectionCounter,
    grants: list[PrivilegeGrant],
) -> None:
    filtered = _filtered_grants(grants)
    if not filtered:
        return
    _print_section_heading(console, counter, "Privileges", _CAPTION_SCHEMA_PRIVILEGES)
    table = _report_table(zebra=len(filtered) > 5)
    table.add_column("Grantee")
    table.add_column("Privilege")
    table.add_column("Grantor", style="dim")
    for g in filtered:
        priv = g.privilege + (" *" if g.with_grant_option else "")
        table.add_row(cell(g.grantee), cell(priv), cell(g.grantor or ""))
    console.print(_indent(table))


def _render_schema_default_privileges(
    console: Console,
    counter: _SectionCounter,
    grants: list[DefaultPrivilegeGrant],
) -> None:
    if not grants:
        return
    _print_section_heading(
        console, counter, "Default privileges", _CAPTION_SCHEMA_DEFAULT_PRIVILEGES
    )
    table = _report_table(zebra=len(grants) > 5)
    table.add_column("Grantee")
    table.add_column("Object type", style="dim")
    table.add_column("Privileges", overflow="fold")
    table.add_column("Granted by", style="dim")
    for g in grants:
        privs = ", ".join(g.privileges)
        if g.with_grant_option:
            privs = f"{privs} *"
        table.add_row(
            cell(g.grantee), cell(g.object_type), cell(privs), cell(g.grantor or "")
        )
    console.print(_indent(table))


def _render_schema_highlights(
    console: Console,
    counter: _SectionCounter,
    desc: SchemaDescription,
) -> None:
    candidates = [
        item
        for item in desc.contents
        if item.size_bytes is not None and item.size_bytes > 0
    ]
    if not candidates:
        return
    top = sorted(candidates, key=lambda it: it.size_bytes or 0, reverse=True)[:5]
    _print_section_heading(console, counter, "Highlights", _CAPTION_SCHEMA_HIGHLIGHTS)
    table = _report_table(zebra=False)
    table.add_column("#", justify="right", style="dim", width=3)
    table.add_column("Name")
    table.add_column("Kind", style="dim")
    table.add_column("Rows", justify="right")
    table.add_column("Size", justify="right")
    for i, item in enumerate(top, start=1):
        table.add_row(
            str(i),
            cell(item.name),
            cell(item.kind),
            _fmt_rows(item.row_estimate),
            _fmt_size(item.size_bytes),
        )
    console.print(_indent(table))


def _render_schema_description(
    console: Console, desc: SchemaDescription, engine: SqlEngine
) -> None:
    _print_title_card_and_gap(
        console,
        title=esc(desc.header.name),
        subtitle="Schema",
        metadata=_schema_title_metadata(desc),
    )

    counter = _SectionCounter()
    _render_schema_privileges(console, counter, desc.privileges)
    _render_schema_default_privileges(console, counter, desc.default_privileges)
    _render_schema_highlights(console, counter, desc)
    if desc.contents:
        _print_section_heading(console, counter, "Contents", _CAPTION_SCHEMA_CONTENTS)
        # An Owner column of blanks would invite the reader to wonder what went
        # wrong. On an engine with no users nothing went wrong, and the
        # Privileges note in _render_not_applicable is where that is explained.
        has_owner = any(item.owner for item in desc.contents)
        table = _report_table(zebra=len(desc.contents) > 5)
        table.add_column("Name")
        table.add_column("Kind", style="dim")
        if has_owner:
            table.add_column("Owner")
        table.add_column("Rows", justify="right")
        table.add_column("Size", justify="right")
        for item in desc.contents:
            row: list[str | Text] = [cell(item.name), cell(item.kind)]
            if has_owner:
                row.append(cell(item.owner))
            row += [_fmt_rows(item.row_estimate), _fmt_size(item.size_bytes)]
            table.add_row(*row)
        console.print(_indent(table))
    _render_not_applicable(console, counter, desc.not_applicable, engine)


def render_description(
    console: Console,
    desc: Description,
    engine: SqlEngine,
) -> None:
    if isinstance(desc, TableDescription):
        _render_table_description(console, desc, engine)
    elif isinstance(desc, ViewDescription):
        _render_view_description(console, desc, engine)
    elif isinstance(desc, SchemaDescription):
        _render_schema_description(console, desc, engine)
    else:
        raise TypeError(f"unsupported description: {type(desc).__name__}")


app = typer.Typer(
    name="describe",
    help="Show metadata for a schema, table, view, or materialized view.",
    invoke_without_command=True,
    no_args_is_help=True,
)


def _split_targets(target: str) -> list[str]:
    """Split a comma-separated target list, ignoring empty/whitespace entries."""
    return [t.strip() for t in target.split(",") if t.strip()]


@app.callback(invoke_without_command=True)
def describe(
    target: str = typer.Argument(
        ...,
        help='"<schema>" or "<schema>.<object>". Comma-separate to describe several '
        '(e.g. "public,public.users,raw.orders").',
    ),
    db_target: str | None = TargetOption,
    engine: SqlEngine | None = EngineOption,
    user: str | None = UserOption,
    password: str | None = PasswordOption,
    database: str | None = DatabaseOption,
    host: str | None = HostOption,
    port: int | None = PortOption,
    sslmode: str | None = SslmodeOption,
    env_prefix: str | None = EnvPrefixOption,
    as_json: bool = JsonOption,
) -> None:
    """Entry point for ``dp db describe <target>``.

    One of the three commands that works on every engine, so it resolves through
    :func:`resolve_any_params_or_exit` and receives whichever param shape the
    target's engine needs. Nothing below has to know which: ``db_session``
    dispatches the driver, ``params.engine`` picks the dialect, and the report
    itself names the sections the engine has no concept of.
    """
    console = Console()
    targets = _split_targets(target)
    if not targets:
        console.print(
            '[red]Error: target must be "<schema>" or "<schema>.<object>"[/red]'
        )
        raise typer.Exit(code=1)

    conn_params = resolve_any_params_or_exit(
        ConnCliParams(
            target=db_target,
            engine=engine,
            user=user,
            password=password,
            database=database,
            host=host,
            port=port,
            sslmode=sslmode,
            env_prefix=env_prefix,
        )
    )

    resolved_engine = conn_params.engine
    failures = 0
    rendered = 0
    json_payload: list[dict] = []
    with db_session(conn_params) as conn, conn.cursor() as cursor:
        for single in targets:
            try:
                ref = resolve_target(cursor, resolved_engine, single)
            except (ValueError, TargetNotFoundError) as exc:
                console.print(f"[red]Error ({esc(single)}): {esc(exc)}[/red]")
                failures += 1
                continue
            if ref.kind == ObjectKind.schema:
                desc: Description = describe_schema(cursor, ref, resolved_engine)
            elif ref.kind == ObjectKind.view:
                desc = describe_view(cursor, ref, resolved_engine)
            else:
                desc = describe_table(cursor, ref, resolved_engine)
            if as_json:
                json_payload.append({"target": single, **dataclasses.asdict(desc)})
            else:
                if rendered > 0:
                    console.print()
                    console.print()
                render_description(console, desc, resolved_engine)
            rendered += 1

    if as_json:
        typer.echo(json.dumps(json_payload, indent=2, default=str))
    if failures and failures == len(targets):
        raise typer.Exit(code=1)
