"""Metadata fetchers for ``dp db describe``.

Returns plain dataclasses so the CLI layer can render them without being
coupled to psycopg. Each fetcher takes an open cursor; callers manage the
connection lifecycle.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from dataplat.services.db.connection import SqlEngine


class ObjectKind(str, Enum):
    """Kind of target the user asked to describe."""

    schema = "schema"
    table = "table"
    view = "view"
    matview = "matview"


class TargetNotFoundError(Exception):
    """Raised when the target schema/object does not exist."""


@dataclass(frozen=True)
class TargetRef:
    """Resolved target: kind + identifiers + Postgres oid for object lookups."""

    kind: ObjectKind
    schema: str
    name: str | None  # None for schema targets
    oid: int | None  # None for schema targets


def parse_target(target: str) -> tuple[str, str | None]:
    """Split ``schema`` or ``schema.object`` into components.

    Raises ``ValueError`` for any other shape.
    """
    cleaned = (target or "").strip()
    if not cleaned:
        raise ValueError('target must be "<schema>" or "<schema>.<object>"')
    parts = cleaned.split(".")
    if len(parts) == 1:
        return parts[0], None
    if len(parts) == 2 and parts[0] and parts[1]:
        return parts[0], parts[1]
    raise ValueError('target must be "<schema>" or "<schema>.<object>"')


def resolve_target(cursor: Any, engine: SqlEngine, target: str) -> TargetRef:
    """Resolve a dotted target into a ``TargetRef`` with kind + oid.

    Queries ``pg_namespace`` for schemas and ``pg_class`` for relations.
    Raises ``TargetNotFoundError`` with a user-facing message on miss.
    """
    schema, obj = parse_target(target)

    if obj is None:
        cursor.execute(
            "SELECT 1 FROM pg_namespace WHERE nspname = %s",
            (schema,),
        )
        row = cursor.fetchone()
        if row is None:
            raise TargetNotFoundError(f'schema "{schema}" not found')
        return TargetRef(kind=ObjectKind.schema, schema=schema, name=None, oid=None)

    cursor.execute(
        """
        SELECT c.oid, c.relkind
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relname = %s
        """,
        (schema, obj),
    )
    row = cursor.fetchone()
    if row is None:
        raise TargetNotFoundError(
            f'"{schema}.{obj}" not found. Try: dp db describe {schema}'
        )
    oid, relkind = row
    kind_map = {
        "r": ObjectKind.table,
        "p": ObjectKind.table,
        "v": ObjectKind.view,
        "m": ObjectKind.matview,
    }
    if relkind not in kind_map:
        raise TargetNotFoundError(f'"{schema}.{obj}" has unsupported kind {relkind!r}')
    return TargetRef(kind=kind_map[relkind], schema=schema, name=obj, oid=oid)


@dataclass(frozen=True)
class ColumnInfo:
    ordinal: int
    name: str
    data_type: str
    nullable: bool
    # Default expression, or "GENERATED ALWAYS/BY DEFAULT AS IDENTITY" for
    # identity columns on PostgreSQL.
    default: str | None
    is_primary_key: bool
    fk_target_table: str | None  # fully qualified, e.g. "public.orgs"
    fk_target_column: str | None
    comment: str | None
    encoding: str | None = None  # Redshift only


_COLUMNS_SQL_POSTGRES = """
SELECT
    a.attnum AS ordinal,
    a.attname AS name,
    pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
    NOT a.attnotnull AS nullable,
    CASE a.attidentity
        WHEN 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
        WHEN 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY'
        ELSE pg_get_expr(ad.adbin, ad.adrelid)
    END AS default_expr,
    COALESCE(pk.is_pk, false) AS is_primary_key,
    fk.target_table AS fk_target_table,
    fk.target_column AS fk_target_column,
    col_description(a.attrelid, a.attnum) AS comment
FROM pg_attribute a
LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
LEFT JOIN LATERAL (
    SELECT true AS is_pk
    FROM pg_index i
    WHERE i.indrelid = a.attrelid
      AND i.indisprimary
      AND a.attnum = ANY(i.indkey)
    LIMIT 1
) pk ON true
LEFT JOIN LATERAL (
    SELECT
        quote_ident(fn.nspname) || '.' || quote_ident(fc.relname) AS target_table,
        fa.attname AS target_column
    FROM pg_constraint con
    JOIN pg_class fc ON fc.oid = con.confrelid
    JOIN pg_namespace fn ON fn.oid = fc.relnamespace
    JOIN pg_attribute fa
      ON fa.attrelid = con.confrelid
     AND fa.attnum = con.confkey[
       array_position(con.conkey, a.attnum)
     ]
    WHERE con.contype = 'f'
      AND con.conrelid = a.attrelid
      AND a.attnum = ANY(con.conkey)
    LIMIT 1
) fk ON true
WHERE a.attrelid = %s AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
"""

_COLUMNS_SQL_REDSHIFT = """
SELECT
    a.attnum AS ordinal,
    a.attname AS name,
    pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
    NOT a.attnotnull AS nullable,
    pg_get_expr(ad.adbin, ad.adrelid) AS default_expr,
    false AS is_primary_key,
    NULL::text AS fk_target_table,
    NULL::text AS fk_target_column,
    col_description(a.attrelid, a.attnum) AS comment,
    (SELECT encoding FROM pg_catalog.pg_attribute_encoding ae
     WHERE ae.attrelid = a.attrelid AND ae.attnum = a.attnum) AS encoding
FROM pg_attribute a
LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
WHERE a.attrelid = %s AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
"""


def fetch_columns(cursor: Any, oid: int, engine: SqlEngine) -> list[ColumnInfo]:
    """Return ordinal-ordered columns for the given relation oid."""
    sql = (
        _COLUMNS_SQL_REDSHIFT if engine == SqlEngine.redshift else _COLUMNS_SQL_POSTGRES
    )
    cursor.execute(sql, (oid,))
    return [ColumnInfo(*row) for row in cursor.fetchall()]


@dataclass(frozen=True)
class PrimaryKeyInfo:
    name: str
    columns: list[str]


@dataclass(frozen=True)
class ForeignKeyInfo:
    name: str
    columns: list[str]
    referenced_table: str  # schema.name
    referenced_columns: list[str]
    on_update: str
    on_delete: str
    deferrable: bool


@dataclass(frozen=True)
class ConstraintInfo:
    name: str
    definition: str


@dataclass(frozen=True)
class ConstraintBundle:
    primary_key: PrimaryKeyInfo | None
    foreign_keys: list[ForeignKeyInfo]
    unique_constraints: list[ConstraintInfo]
    check_constraints: list[ConstraintInfo]


_FK_ACTION_MAP = {
    "a": "NO ACTION",
    "r": "RESTRICT",
    "c": "CASCADE",
    "n": "SET NULL",
    "d": "SET DEFAULT",
}


_CONSTRAINTS_SQL = """
SELECT
    c.conname AS name,
    c.contype AS kind,
    pg_get_constraintdef(c.oid, true) AS definition,
    COALESCE(
      (SELECT array_agg(a.attname ORDER BY k.ord)
       FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
       JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum),
      '{}'::text[]
    ) AS local_columns,
    CASE WHEN c.contype = 'f' THEN
      quote_ident(fn.nspname) || '.' || quote_ident(fc.relname)
    END AS referenced_table,
    CASE WHEN c.contype = 'f' THEN
      (SELECT array_agg(fa.attname ORDER BY k.ord)
       FROM unnest(c.confkey) WITH ORDINALITY AS k(attnum, ord)
       JOIN pg_attribute fa ON fa.attrelid = c.confrelid AND fa.attnum = k.attnum)
    END AS referenced_columns,
    CASE WHEN c.contype = 'f' THEN c.confdeltype END AS confdeltype,
    CASE WHEN c.contype = 'f' THEN c.confupdtype END AS confupdtype,
    CASE WHEN c.contype = 'f' THEN c.condeferrable END AS deferrable
FROM pg_constraint c
LEFT JOIN pg_class fc ON fc.oid = c.confrelid
LEFT JOIN pg_namespace fn ON fn.oid = fc.relnamespace
WHERE c.conrelid = %s
ORDER BY CASE c.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 ELSE 3 END,
         c.conname
"""


@dataclass(frozen=True)
class IndexInfo:
    name: str
    columns: list[str]
    unique: bool
    primary: bool
    method: str
    size_bytes: int | None
    predicate: str | None


_INDEXES_SQL_POSTGRES = """
SELECT
    ic.relname AS name,
    ARRAY(
      SELECT pg_get_indexdef(i.indexrelid, k + 1, true)
      FROM generate_subscripts(i.indkey, 1) AS k
    ) AS columns,
    i.indisunique AS unique,
    i.indisprimary AS primary,
    am.amname AS method,
    -- Same pg_partition_tree() caveat as the relation header: the tree is
    -- empty for an index that is neither partitioned nor a partition, so
    -- without the fallback every ordinary index reported 0 bytes.
    COALESCE(
      (SELECT SUM(pg_relation_size(p.relid))
       FROM pg_partition_tree(i.indexrelid) p),
      pg_relation_size(i.indexrelid)
    )::bigint AS size_bytes,
    CASE WHEN i.indpred IS NOT NULL
         THEN pg_get_expr(i.indpred, i.indrelid, true)
    END AS predicate
FROM pg_index i
JOIN pg_class ic ON ic.oid = i.indexrelid
JOIN pg_am am ON am.oid = ic.relam
WHERE i.indrelid = %s
ORDER BY i.indisprimary DESC, i.indisunique DESC, ic.relname
"""

_INDEXES_SQL_REDSHIFT = """
SELECT ic.relname, ARRAY[]::text[], i.indisunique, i.indisprimary,
       'btree', NULL::bigint, NULL::text
FROM pg_index i
JOIN pg_class ic ON ic.oid = i.indexrelid
WHERE i.indrelid = %s
ORDER BY ic.relname
"""


def fetch_indexes(cursor: Any, oid: int, engine: SqlEngine) -> list[IndexInfo]:
    """Return indexes for the given relation oid."""
    sql = (
        _INDEXES_SQL_REDSHIFT if engine == SqlEngine.redshift else _INDEXES_SQL_POSTGRES
    )
    cursor.execute(sql, (oid,))
    return [IndexInfo(*row) for row in cursor.fetchall()]


@dataclass(frozen=True)
class RelationHeader:
    schema: str
    name: str
    owner: str
    tablespace: str | None
    comment: str | None
    row_estimate: int | None
    total_size: int | None
    table_size: int | None
    index_size: int | None
    toast_size: int | None


@dataclass(frozen=True)
class PrivilegeGrant:
    grantee: str
    privilege: str  # "SELECT", "INSERT", ..., or "OWNER" for ownership row
    with_grant_option: bool
    grantor: str


_RELATION_HEADER_SQL_POSTGRES = """
SELECT
    n.nspname,
    c.relname,
    pg_get_userbyid(c.relowner) AS owner,
    COALESCE(t.spcname, 'pg_default') AS tablespace,
    obj_description(c.oid, 'pg_class') AS comment,
    -- pg_partition_tree() returns NO rows for a relation that is neither a
    -- partition nor partitioned, so each aggregate below needs the fallback
    -- arm of its COALESCE: without one an ordinary table reported 0 bytes and
    -- an unknown row count. Partitioned parents are excluded from the row sum
    -- because pg_class.reltuples on a parent already aggregates its
    -- partitions -- adding both counts every row twice.
    COALESCE(
      (SELECT SUM(pc.reltuples)::bigint
         FROM pg_partition_tree(c.oid) p
         JOIN pg_class pc ON pc.oid = p.relid
        WHERE pc.reltuples >= 0 AND pc.relkind <> 'p'),
      CASE WHEN c.reltuples >= 0 THEN c.reltuples::bigint END
    ) AS row_estimate,
    COALESCE(
      (SELECT SUM(pg_total_relation_size(p.relid))
         FROM pg_partition_tree(c.oid) p),
      pg_total_relation_size(c.oid)
    )::bigint AS total_size,
    COALESCE(
      (SELECT SUM(pg_relation_size(p.relid))
         FROM pg_partition_tree(c.oid) p),
      pg_relation_size(c.oid)
    )::bigint AS table_size,
    COALESCE(
      (SELECT SUM(pg_indexes_size(p.relid))
         FROM pg_partition_tree(c.oid) p),
      pg_indexes_size(c.oid)
    )::bigint AS index_size,
    COALESCE(
      (SELECT SUM(
                pg_total_relation_size(p.relid)
              - pg_relation_size(p.relid)
              - pg_indexes_size(p.relid)
              )
         FROM pg_partition_tree(c.oid) p),
      pg_total_relation_size(c.oid)
      - pg_relation_size(c.oid)
      - pg_indexes_size(c.oid)
    )::bigint AS toast_size
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_tablespace t ON t.oid = c.reltablespace
WHERE c.oid = %s
"""

_RELATION_HEADER_SQL_REDSHIFT = """
SELECT
    n.nspname,
    c.relname,
    pg_get_userbyid(c.relowner) AS owner,
    NULL::text AS tablespace,
    obj_description(c.oid, 'pg_class') AS comment,
    (SELECT tbl_rows FROM svv_table_info
     WHERE "schema" = n.nspname AND "table" = c.relname) AS row_estimate,
    (SELECT size::bigint * 1024 * 1024 FROM svv_table_info
     WHERE "schema" = n.nspname AND "table" = c.relname) AS total_size,
    NULL::bigint, NULL::bigint, NULL::bigint
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.oid = %s
"""


def fetch_relation_header(cursor: Any, oid: int, engine: SqlEngine) -> RelationHeader:
    sql = (
        _RELATION_HEADER_SQL_REDSHIFT
        if engine == SqlEngine.redshift
        else _RELATION_HEADER_SQL_POSTGRES
    )
    cursor.execute(sql, (oid,))
    row = cursor.fetchone()
    if row is None:
        raise TargetNotFoundError(f"relation with oid {oid} not found")
    return RelationHeader(*row)


_PRIVILEGES_SQL = """
SELECT grantee, privilege_type AS privilege,
       is_grantable = 'YES' AS with_grant_option,
       grantor
FROM information_schema.role_table_grants
WHERE table_schema = %s AND table_name = %s
UNION ALL
SELECT pg_get_userbyid(c.relowner), 'OWNER', false, ''
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = %s AND c.relname = %s
ORDER BY grantee, privilege
"""


def fetch_relation_privileges(
    cursor: Any, schema: str, name: str
) -> list[PrivilegeGrant]:
    cursor.execute(_PRIVILEGES_SQL, (schema, name, schema, name))
    return [PrivilegeGrant(*row) for row in cursor.fetchall()]


@dataclass(frozen=True)
class TriggerInfo:
    name: str
    timing: str  # BEFORE / AFTER / INSTEAD OF
    events: str  # e.g. "INSERT OR UPDATE"
    function: str


@dataclass(frozen=True)
class PolicyInfo:
    name: str
    command: str  # ALL, SELECT, INSERT, UPDATE, DELETE
    roles: list[str]
    using: str | None
    with_check: str | None


@dataclass(frozen=True)
class PartitioningInfo:
    parent: str | None
    strategy: str | None  # RANGE / LIST / HASH
    partition_key: str | None
    children: list[tuple[str, str]]  # (name, bounds)


_TRIGGERS_SQL = """
SELECT
    t.tgname AS name,
    CASE WHEN (t.tgtype & 2) <> 0 THEN 'BEFORE'
         WHEN (t.tgtype & 64) <> 0 THEN 'INSTEAD OF'
         ELSE 'AFTER' END AS timing,
    pg_catalog.array_to_string(ARRAY[
        CASE WHEN (t.tgtype & 4)  <> 0 THEN 'INSERT' END,
        CASE WHEN (t.tgtype & 8)  <> 0 THEN 'DELETE' END,
        CASE WHEN (t.tgtype & 16) <> 0 THEN 'UPDATE' END,
        CASE WHEN (t.tgtype & 32) <> 0 THEN 'TRUNCATE' END
    ], ' OR ') AS events,
    pg_get_triggerdef(t.oid, true) AS function
FROM pg_trigger t
WHERE t.tgrelid = %s AND NOT t.tgisinternal
ORDER BY t.tgname
"""


def fetch_triggers(cursor: Any, oid: int, engine: SqlEngine) -> list[TriggerInfo]:
    if engine == SqlEngine.redshift:
        return []
    cursor.execute(_TRIGGERS_SQL, (oid,))
    return [TriggerInfo(*row) for row in cursor.fetchall()]


_RLS_ENABLED_SQL = "SELECT relrowsecurity FROM pg_class WHERE oid = %s"
_POLICIES_SQL = """
SELECT
    pol.polname AS name,
    CASE pol.polcmd WHEN 'r' THEN 'SELECT' WHEN 'a' THEN 'INSERT'
                    WHEN 'w' THEN 'UPDATE' WHEN 'd' THEN 'DELETE'
                    ELSE 'ALL' END AS command,
    COALESCE(
      (SELECT array_agg(rolname) FROM pg_roles WHERE oid = ANY(pol.polroles)),
      ARRAY['public']
    ) AS roles,
    pg_get_expr(pol.polqual, pol.polrelid, true) AS using_expr,
    pg_get_expr(pol.polwithcheck, pol.polrelid, true) AS with_check
FROM pg_policy pol
WHERE pol.polrelid = %s
ORDER BY pol.polname
"""


def fetch_policies(
    cursor: Any, oid: int, engine: SqlEngine
) -> tuple[list[PolicyInfo], bool]:
    if engine == SqlEngine.redshift:
        return [], False
    cursor.execute(_RLS_ENABLED_SQL, (oid,))
    row = cursor.fetchone()
    enabled = bool(row[0]) if row else False
    cursor.execute(_POLICIES_SQL, (oid,))
    policies = [PolicyInfo(*r) for r in cursor.fetchall()]
    return policies, enabled


_PARTITION_CHILD_PARENT_SQL = """
SELECT quote_ident(pn.nspname) || '.' || quote_ident(pc.relname)
FROM pg_inherits inh
JOIN pg_class pc ON pc.oid = inh.inhparent
JOIN pg_namespace pn ON pn.oid = pc.relnamespace
WHERE inh.inhrelid = %s
"""


_PARTITION_ROOT_STRATEGY_SQL = """
SELECT CASE partstrat
    WHEN 'r' THEN 'RANGE'
    WHEN 'l' THEN 'LIST'
    WHEN 'h' THEN 'HASH'
END
FROM pg_partitioned_table
WHERE partrelid = %s
"""

_PARTITION_CHILDREN_SQL = """
SELECT
    quote_ident(cn.nspname) || '.' || quote_ident(cc.relname) AS child,
    pg_get_expr(cc.relpartbound, cc.oid, true) AS bounds
FROM pg_inherits inh
JOIN pg_class cc ON cc.oid = inh.inhrelid
JOIN pg_namespace cn ON cn.oid = cc.relnamespace
WHERE inh.inhparent = %s
ORDER BY cc.relname
"""


def fetch_partitioning(cursor: Any, oid: int, engine: SqlEngine) -> PartitioningInfo:
    if engine == SqlEngine.redshift:
        return PartitioningInfo(
            parent=None, strategy=None, partition_key=None, children=[]
        )
    cursor.execute(_PARTITION_CHILD_PARENT_SQL, (oid,))
    parent_row = cursor.fetchone()
    parent = parent_row[0] if parent_row else None
    cursor.execute(_PARTITION_ROOT_STRATEGY_SQL, (oid,))
    strat_row = cursor.fetchone()
    strategy = strat_row[0] if strat_row else None
    cursor.execute("SELECT pg_get_partkeydef(%s)", (oid,))
    pk_row = cursor.fetchone()
    partition_key = pk_row[0] if pk_row and pk_row[0] else None
    cursor.execute(_PARTITION_CHILDREN_SQL, (oid,))
    children = [(r[0], r[1]) for r in cursor.fetchall()]
    return PartitioningInfo(
        parent=parent, strategy=strategy, partition_key=partition_key, children=children
    )


@dataclass(frozen=True)
class ViewDefinition:
    sql: str
    is_updatable: bool
    check_option: str | None


@dataclass(frozen=True)
class DependencyEdge:
    qualified_name: str
    kind: str


_VIEW_DEFINITION_SQL = """
SELECT
    pg_get_viewdef(c.oid, true) AS sql,
    (SELECT is_updatable FROM information_schema.views
     WHERE table_schema = n.nspname AND table_name = c.relname) AS is_updatable,
    (SELECT check_option FROM information_schema.views
     WHERE table_schema = n.nspname AND table_name = c.relname) AS check_option
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.oid = %s
"""


_VIEW_DEFINITION_SQL_REDSHIFT = "SELECT pg_get_viewdef(%s, true) AS sql"


_DEPS_UPSTREAM_SQL = """
SELECT DISTINCT
    quote_ident(sn.nspname) || '.' || quote_ident(sc.relname) AS name,
    sc.relkind AS kind
FROM pg_rewrite r
JOIN pg_depend d ON d.objid = r.oid AND d.classid = 'pg_rewrite'::regclass
JOIN pg_class sc ON sc.oid = d.refobjid
JOIN pg_namespace sn ON sn.oid = sc.relnamespace
WHERE r.ev_class = %s
  AND d.refobjid <> %s
  AND sc.relkind IN ('r','v','m','f','p')
ORDER BY name
"""


_DEPS_DOWNSTREAM_SQL = """
SELECT DISTINCT
    quote_ident(tn.nspname) || '.' || quote_ident(tc.relname) AS name,
    tc.relkind AS kind
FROM pg_rewrite r
JOIN pg_depend d ON d.objid = r.oid AND d.classid = 'pg_rewrite'::regclass
JOIN pg_class tc ON tc.oid = r.ev_class
JOIN pg_namespace tn ON tn.oid = tc.relnamespace
WHERE d.refobjid = %s
  AND r.ev_class <> %s
  AND tc.relkind IN ('v','m')
ORDER BY name
"""


_KIND_LABEL = {
    "r": "table",
    "v": "view",
    "m": "matview",
    "f": "foreign table",
    "p": "partitioned table",
    "S": "sequence",
    "i": "index",
}


def fetch_view_definition(cursor: Any, oid: int, engine: SqlEngine) -> ViewDefinition:
    """Return the SQL definition + updatability info for a view/matview."""
    if engine == SqlEngine.redshift:
        cursor.execute(_VIEW_DEFINITION_SQL_REDSHIFT, (oid,))
        row = cursor.fetchone()
        if row is None:
            raise TargetNotFoundError(f"view with oid {oid} not found")
        (sql,) = row
        if sql is None:
            raise TargetNotFoundError(f"view with oid {oid} not found")
        return ViewDefinition(sql=sql, is_updatable=False, check_option=None)
    cursor.execute(_VIEW_DEFINITION_SQL, (oid,))
    row = cursor.fetchone()
    if row is None:
        raise TargetNotFoundError(f"view with oid {oid} not found")
    sql, is_updatable, check_option = row
    # pg_get_viewdef() does not error on a non-view oid, it returns NULL, so a
    # table's oid produces a row whose definition is missing. Reject it the way
    # the Redshift branch above does: returning ViewDefinition(sql=None) would
    # break this dataclass's own `sql: str` contract for every caller.
    if sql is None:
        raise TargetNotFoundError(f"view with oid {oid} not found")
    updatable = isinstance(is_updatable, str) and is_updatable.upper() == "YES"
    if check_option is None or check_option == "NONE":
        check_option_value: str | None = None
    else:
        check_option_value = check_option
    return ViewDefinition(
        sql=sql, is_updatable=updatable, check_option=check_option_value
    )


def fetch_dependencies(
    cursor: Any, oid: int, direction: str, engine: SqlEngine
) -> list[DependencyEdge]:
    """Return upstream or downstream dependency edges for the given relation."""
    if engine == SqlEngine.redshift:
        return []
    if direction == "upstream":
        sql = _DEPS_UPSTREAM_SQL
    elif direction == "downstream":
        sql = _DEPS_DOWNSTREAM_SQL
    else:
        raise ValueError(
            f"direction must be 'upstream' or 'downstream', got {direction!r}"
        )
    cursor.execute(sql, (oid, oid))
    return [
        DependencyEdge(qualified_name=name, kind=_KIND_LABEL.get(kind, kind))
        for name, kind in cursor.fetchall()
    ]


@dataclass(frozen=True)
class SchemaHeader:
    name: str
    owner: str
    comment: str | None


@dataclass(frozen=True)
class SchemaContentItem:
    name: str
    kind: str
    owner: str
    row_estimate: int | None
    size_bytes: int | None


_SCHEMA_HEADER_SQL = """
SELECT n.nspname, pg_get_userbyid(n.nspowner),
       obj_description(n.oid, 'pg_namespace')
FROM pg_namespace n
WHERE n.nspname = %s
"""


_SCHEMA_CONTENTS_SQL_POSTGRES = """
SELECT
    c.relname AS name,
    c.relkind AS kind,
    pg_get_userbyid(c.relowner) AS owner,
    CASE WHEN c.relkind IN ('r','m','p') THEN c.reltuples::bigint END AS row_estimate,
    CASE WHEN c.relkind IN ('r','m','p','i','S')
         THEN pg_total_relation_size(c.oid)
    END AS size_bytes
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = %s
  AND c.relkind IN ('r','v','m','p','S','f')
ORDER BY c.relkind, c.relname
"""


_SCHEMA_CONTENTS_SQL_REDSHIFT = """
SELECT
    c.relname, c.relkind, pg_get_userbyid(c.relowner),
    (SELECT tbl_rows FROM svv_table_info
     WHERE "schema" = %s AND "table" = c.relname),
    (SELECT size::bigint * 1024 * 1024 FROM svv_table_info
     WHERE "schema" = %s AND "table" = c.relname)
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = %s
  AND c.relkind IN ('r','v','m','S','f')
ORDER BY c.relkind, c.relname
"""


# PostgreSQL exposes schema ACLs only through pg_namespace.nspacl; there is no
# information_schema view for them. usage_privileges reports DOMAIN, COLLATION,
# FDW, foreign server and sequence object types and never 'SCHEMA', so the
# USAGE half of the old shared query silently matched zero rows and every
# GRANT USAGE ON SCHEMA was missing from the report.
#
# The COALESCE is load-bearing: nspacl stays NULL until the first GRANT or
# REVOKE touches the schema, and NULL means "the built-in default" -- the owner
# holding USAGE + CREATE -- not "nobody holds anything". acldefault('n', owner)
# materialises that default so a freshly created schema still reports its
# owner's privileges.
#
# Reading the ACL also makes grantor and WITH GRANT OPTION truthful: the CREATE
# half of the old query derived grantees from has_schema_privilege() and had to
# hardcode grantor='' and with_grant_option=false.
_SCHEMA_PRIVILEGES_SQL_POSTGRES = """
SELECT
    CASE WHEN (acl).grantee = 0 THEN 'PUBLIC'
         ELSE pg_get_userbyid((acl).grantee) END AS grantee,
    (acl).privilege_type AS privilege_type,
    (acl).is_grantable AS with_grant_option,
    pg_get_userbyid((acl).grantor) AS grantor
FROM pg_namespace n
CROSS JOIN LATERAL aclexplode(COALESCE(n.nspacl, acldefault('n', n.nspowner))) AS acl
WHERE n.nspname = %s
ORDER BY grantee, privilege_type
"""


# Not the aclexplode form above: Redshift has no aclexplode(), and no cluster is
# available to test a replacement against.
#
# The USAGE half used to read information_schema.usage_privileges filtered to
# object_type = 'SCHEMA', which the SQL standard defines over domains,
# collations and sequences — never schemas. It returned zero rows on every
# server, so a GRANT USAGE ON SCHEMA was invisible here exactly as it was on
# PostgreSQL. It is replaced by a has_schema_privilege() scan mirroring the
# CREATE half directly below, which this same query has always run against
# Redshift: same function, same catalog, same shape, only the privilege string
# differs (CONTRIBUTING, evidence 2 — internal precedent on this very path).
#
# Known limitation, shared with the CREATE half and unchanged: a privilege scan
# cannot report a grantor or a grant option, so both are reported empty, and
# roles holding the privilege only through membership appear as their own rows.
# The PostgreSQL path reads the ACL and does better on both counts.
_SCHEMA_PRIVILEGES_SQL_REDSHIFT = """
SELECT grantee, 'USAGE', false, ''
FROM (
    SELECT r.rolname AS grantee
    FROM pg_roles r
    WHERE has_schema_privilege(r.rolname, %s, 'USAGE')
) u
UNION ALL
SELECT grantee, 'CREATE', false, ''
FROM (
    SELECT r.rolname AS grantee
    FROM pg_roles r
    WHERE has_schema_privilege(r.rolname, %s, 'CREATE')
) c
ORDER BY grantee, privilege_type
"""


_SCHEMA_DEFAULT_PRIVILEGES_SQL = """
SELECT
    CASE WHEN (acl).grantee = 0 THEN 'PUBLIC'
         ELSE pg_get_userbyid((acl).grantee) END AS grantee,
    CASE d.defaclobjtype
        WHEN 'r' THEN 'TABLE'
        WHEN 'S' THEN 'SEQUENCE'
        WHEN 'f' THEN 'FUNCTION'
        WHEN 'T' THEN 'TYPE'
        WHEN 'n' THEN 'SCHEMA'
        ELSE d.defaclobjtype::text
    END AS object_type,
    array_agg((acl).privilege_type ORDER BY (acl).privilege_type) AS privileges,
    bool_or((acl).is_grantable) AS with_grant_option,
    pg_get_userbyid(d.defaclrole) AS grantor
FROM pg_default_acl d
JOIN pg_namespace n ON n.oid = d.defaclnamespace
CROSS JOIN LATERAL aclexplode(d.defaclacl) AS acl
WHERE n.nspname = %s
GROUP BY (acl).grantee, d.defaclobjtype, d.defaclrole
ORDER BY object_type, grantee
"""


def fetch_schema_header(cursor: Any, schema: str) -> SchemaHeader:
    """Return the schema header (name, owner, comment)."""
    cursor.execute(_SCHEMA_HEADER_SQL, (schema,))
    row = cursor.fetchone()
    if row is None:
        raise TargetNotFoundError(f'schema "{schema}" not found')
    return SchemaHeader(*row)


def fetch_schema_contents(
    cursor: Any, schema: str, engine: SqlEngine
) -> list[SchemaContentItem]:
    """Return relations contained in the schema, labelled by kind."""
    if engine == SqlEngine.redshift:
        cursor.execute(_SCHEMA_CONTENTS_SQL_REDSHIFT, (schema, schema, schema))
    else:
        cursor.execute(_SCHEMA_CONTENTS_SQL_POSTGRES, (schema,))
    return [
        SchemaContentItem(
            name=name,
            kind=_KIND_LABEL.get(kind, kind),
            owner=owner,
            row_estimate=row_estimate,
            size_bytes=size_bytes,
        )
        for name, kind, owner, row_estimate, size_bytes in cursor.fetchall()
    ]


def fetch_schema_privileges(
    cursor: Any, schema: str, engine: SqlEngine
) -> list[PrivilegeGrant]:
    """Return USAGE + CREATE grants for the schema.

    On PostgreSQL these come from ``pg_namespace.nspacl``, which lists explicit
    ACL entries plus the owner's implicit default; a role that only holds the
    privilege through membership in a granted role is not a separate row.
    """
    if engine == SqlEngine.redshift:
        cursor.execute(_SCHEMA_PRIVILEGES_SQL_REDSHIFT, (schema, schema))
    else:
        cursor.execute(_SCHEMA_PRIVILEGES_SQL_POSTGRES, (schema,))
    return [PrivilegeGrant(*row) for row in cursor.fetchall()]


@dataclass(frozen=True)
class DefaultPrivilegeGrant:
    """A row from ``pg_default_acl`` — privileges that future objects inherit.

    Set via
    ``ALTER DEFAULT PRIVILEGES IN SCHEMA <schema> GRANT ... ON TABLES TO <role>``.
    """

    grantee: str
    object_type: str  # TABLE / SEQUENCE / FUNCTION / TYPE / SCHEMA
    privileges: list[str]
    with_grant_option: bool
    grantor: str  # the role whose creations the defaults apply to


def fetch_schema_default_privileges(
    cursor: Any, schema: str, engine: SqlEngine
) -> list[DefaultPrivilegeGrant]:
    """Return default privileges defined for future objects in the schema.

    Reads ``pg_default_acl`` aggregated by (grantee, object type, grantor role).
    Returns ``[]`` on Redshift (lacks ``pg_default_acl`` semantics).
    """
    if engine == SqlEngine.redshift:
        return []
    cursor.execute(_SCHEMA_DEFAULT_PRIVILEGES_SQL, (schema,))
    return [
        DefaultPrivilegeGrant(
            grantee=grantee,
            object_type=object_type,
            privileges=list(privileges or []),
            with_grant_option=bool(with_grant_option),
            grantor=grantor or "",
        )
        for (
            grantee,
            object_type,
            privileges,
            with_grant_option,
            grantor,
        ) in cursor.fetchall()
    ]


@dataclass(frozen=True)
class RedshiftDistribution:
    diststyle: str
    distkey: str | None
    sortkey_style: str | None
    sortkeys: list[str]


@dataclass(frozen=True)
class RedshiftTableStats:
    skew_rows: float | None
    unsorted_pct: float | None
    stats_off: bool | None


_REDSHIFT_DIST_SQL = """
SELECT
    diststyle, distkey, sortkey1 AS sortkey_style,
    ARRAY(
      SELECT column_name
      FROM svv_redshift_columns
      WHERE schema_name = %s AND table_name = %s AND sortkey_position > 0
      ORDER BY sortkey_position
    ) AS sortkeys
FROM svv_table_info
WHERE "schema" = %s AND "table" = %s
"""


_REDSHIFT_STATS_SQL = """
SELECT skew_rows, unsorted, stats_off
FROM svv_table_info
WHERE "schema" = %s AND "table" = %s
"""


def fetch_redshift_distribution(
    cursor: Any, schema: str, name: str
) -> RedshiftDistribution | None:
    """Return Redshift distribution + sort key info, or None if no row."""
    cursor.execute(_REDSHIFT_DIST_SQL, (schema, name, schema, name))
    row = cursor.fetchone()
    if row is None:
        return None
    diststyle, distkey, sortkey_style, sortkeys = row
    return RedshiftDistribution(
        diststyle=diststyle,
        distkey=distkey,
        sortkey_style=sortkey_style,
        sortkeys=list(sortkeys or []),
    )


def fetch_redshift_table_stats(
    cursor: Any, schema: str, name: str
) -> RedshiftTableStats | None:
    """Return Redshift table stats (skew, unsorted %, stats_off), or None if no row."""
    cursor.execute(_REDSHIFT_STATS_SQL, (schema, name))
    row = cursor.fetchone()
    if row is None:
        return None
    skew_rows, unsorted_pct, stats_off = row
    return RedshiftTableStats(
        skew_rows=skew_rows, unsorted_pct=unsorted_pct, stats_off=stats_off
    )


@dataclass(frozen=True)
class TableDescription:
    ref: TargetRef
    header: RelationHeader
    columns: list[ColumnInfo]
    constraints: ConstraintBundle
    indexes: list[IndexInfo]
    privileges: list[PrivilegeGrant]
    triggers: list[TriggerInfo]
    policies: list[PolicyInfo]
    policies_enabled: bool
    partitioning: PartitioningInfo
    redshift_distribution: RedshiftDistribution | None
    redshift_stats: RedshiftTableStats | None
    definition: str | None  # mview only


@dataclass(frozen=True)
class ViewDescription:
    ref: TargetRef
    header: RelationHeader
    columns: list[ColumnInfo]
    definition: ViewDefinition
    upstream: list[DependencyEdge]
    downstream: list[DependencyEdge]
    privileges: list[PrivilegeGrant]
    triggers: list[TriggerInfo]


@dataclass(frozen=True)
class SchemaDescription:
    header: SchemaHeader
    privileges: list[PrivilegeGrant]
    contents: list[SchemaContentItem]
    default_privileges: list[DefaultPrivilegeGrant] = field(default_factory=list)


def describe_table(cursor: Any, ref: TargetRef, engine: SqlEngine) -> TableDescription:
    """Compose a full table/matview description by invoking each fetcher."""
    assert ref.oid is not None and ref.name is not None
    header = fetch_relation_header(cursor, ref.oid, engine)
    columns = fetch_columns(cursor, ref.oid, engine)
    constraints = fetch_constraints(cursor, ref.oid, engine)
    indexes = fetch_indexes(cursor, ref.oid, engine)
    privileges = fetch_relation_privileges(cursor, ref.schema, ref.name)
    triggers = fetch_triggers(cursor, ref.oid, engine)
    policies, policies_enabled = fetch_policies(cursor, ref.oid, engine)
    partitioning = fetch_partitioning(cursor, ref.oid, engine)

    redshift_distribution: RedshiftDistribution | None = None
    redshift_stats: RedshiftTableStats | None = None
    if engine == SqlEngine.redshift:
        redshift_distribution = fetch_redshift_distribution(
            cursor, ref.schema, ref.name
        )
        redshift_stats = fetch_redshift_table_stats(cursor, ref.schema, ref.name)

    definition: str | None = None
    if ref.kind == ObjectKind.matview and engine == SqlEngine.postgresql:
        definition = fetch_view_definition(cursor, ref.oid, engine).sql

    return TableDescription(
        ref=ref,
        header=header,
        columns=columns,
        constraints=constraints,
        indexes=indexes,
        privileges=privileges,
        triggers=triggers,
        policies=policies,
        policies_enabled=policies_enabled,
        partitioning=partitioning,
        redshift_distribution=redshift_distribution,
        redshift_stats=redshift_stats,
        definition=definition,
    )


def describe_view(cursor: Any, ref: TargetRef, engine: SqlEngine) -> ViewDescription:
    """Compose a full view description by invoking each fetcher."""
    assert ref.oid is not None and ref.name is not None
    header = fetch_relation_header(cursor, ref.oid, engine)
    columns = fetch_columns(cursor, ref.oid, engine)
    definition = fetch_view_definition(cursor, ref.oid, engine)
    upstream = fetch_dependencies(cursor, ref.oid, direction="upstream", engine=engine)
    downstream = fetch_dependencies(
        cursor, ref.oid, direction="downstream", engine=engine
    )
    privileges = fetch_relation_privileges(cursor, ref.schema, ref.name)
    triggers = fetch_triggers(cursor, ref.oid, engine)
    return ViewDescription(
        ref=ref,
        header=header,
        columns=columns,
        definition=definition,
        upstream=upstream,
        downstream=downstream,
        privileges=privileges,
        triggers=triggers,
    )


def describe_schema(
    cursor: Any, ref: TargetRef, engine: SqlEngine
) -> SchemaDescription:
    """Compose a full schema description by invoking each fetcher."""
    header = fetch_schema_header(cursor, ref.schema)
    privileges = fetch_schema_privileges(cursor, ref.schema, engine)
    default_privileges = fetch_schema_default_privileges(cursor, ref.schema, engine)
    contents = fetch_schema_contents(cursor, ref.schema, engine)
    return SchemaDescription(
        header=header,
        privileges=privileges,
        contents=contents,
        default_privileges=default_privileges,
    )


def fetch_constraints(cursor: Any, oid: int, engine: SqlEngine) -> ConstraintBundle:
    if engine == SqlEngine.redshift:
        return ConstraintBundle(
            primary_key=None,
            foreign_keys=[],
            unique_constraints=[],
            check_constraints=[],
        )
    cursor.execute(_CONSTRAINTS_SQL, (oid,))
    pk: PrimaryKeyInfo | None = None
    fks: list[ForeignKeyInfo] = []
    uniques: list[ConstraintInfo] = []
    checks: list[ConstraintInfo] = []
    for (
        name,
        kind,
        defn,
        local_cols,
        ref_table,
        ref_cols,
        del_t,
        upd_t,
        deferrable,
    ) in cursor.fetchall():
        if kind == "p":
            pk = PrimaryKeyInfo(name=name, columns=list(local_cols))
        elif kind == "f":
            fks.append(
                ForeignKeyInfo(
                    name=name,
                    columns=list(local_cols),
                    referenced_table=ref_table,
                    referenced_columns=list(ref_cols or []),
                    on_update=_FK_ACTION_MAP.get(upd_t, "NO ACTION"),
                    on_delete=_FK_ACTION_MAP.get(del_t, "NO ACTION"),
                    deferrable=bool(deferrable),
                )
            )
        elif kind == "u":
            uniques.append(ConstraintInfo(name=name, definition=defn))
        elif kind == "c":
            checks.append(ConstraintInfo(name=name, definition=defn))
    return ConstraintBundle(pk, fks, uniques, checks)
